### ISSUE TITLE
Reflex does not work with parallel batch experiment

### ISSUE THREAD

**Issue by curiosity29** [gama-platform/gama.old#3575]
**Describe the bug**
When using the parallel option for batch experiment, the reflex in the experiment doesn't executed each simulation.
Also, it does not matter whether I set the parallel is true or false in the batch, it always run as specified in the reference (help/preference/execution/In batch mode, allow to run simulations with different parameter sets in parallel).
**To Reproduce**
Using this model:
[test.txt](https://github.com/gama-platform/gama/files/10349806/test.txt)

**Expected behavior**
It should print out numbers from 1 to 10, not necessary in order but at least all of them.

**Screenshots**
![test0501](https://user-images.githubusercontent.com/62107278/210714784-5b91f228-6854-49ab-9d9a-818ba3ef9ae2.png)

**GAMA version: 1.9.0**
 
**Additional context**
It's very confusing that it shown 0 run, 0 simulation when done and parameter x is at 5 all the time.

**Comment by AlexisDrogoul** [comment]
Actually, there are a number of things that needs to be cleared out here: 

1. When you ask the batch experiment to run its simulations in parallel (by forcing the preference), it runs all of them and executes the reflex you have defined. All the simulations are then run during one step of the experiment. Which is why only 10 is written. When you do not run simulations in parallel, the experiment executes one simulation every step, which explains that it writes the different numbers. If you change your model to something like : 

```

model test

global
{
	int x <- 5;
	
	reflex write_something
	{
		write x;
	}
}

experiment batch type: batch until: cycle > 0 parallel: 4
{
	
	init {
		gama.pref_parallel_simulations_all <- true;
		gama.pref_parallel_simulations <- true;
	}
	
	parameter "x" var: x min:1 max: 10 step: 1;


}
```

you will obtain the kind of output you were expecting in all cases (parallel or not) as the message is now written by the simulations (and not the experiment).

2. The `parallel: ` facet was indeed not working at the level of experiments. I have fixed that (it's already committed in 58c7373f3aaea35856c69dbdc78efd4fb9002306). 

3. I do not really understand why we have two preferences for experiments and batch experiments regarding the parallelism. I would suspect that only one preference would be enough, and that it could be managed by the `parallel:` facet as well. However, I let @ptaillandier give his opinion on this, as he has been the implementer of this feature I think.

**Comment by curiosity29** [comment]
> Actually, there are a number of things that needs to be cleared out here:
> 
> 1. When you ask the batch experiment to run its simulations in parallel (by forcing the preference), it runs all of them and executes the reflex you have defined. All the simulations are then run during one step of the experiment. Which is why only 10 is written. When you do not run simulations in parallel, the experiment executes one simulation every step, which explains that it writes the different numbers. If you change your model to something like :
> 
> ```
> 
> model test
> 
> global
> {
> 	int x <- 5;
> 	
> 	reflex write_something
> 	{
> 		write x;
> 	}
> }
> 
> experiment batch type: batch until: cycle > 0 parallel: 4
> {
> 	
> 	init {
> 		gama.pref_parallel_simulations_all <- true;
> 		gama.pref_parallel_simulations <- true;
> 	}
> 	
> 	parameter "x" var: x min:1 max: 10 step: 1;
> 
> 
> }
> ```
> 
> you will obtain the kind of output you were expecting in all cases (parallel or not) as the message is now written by the simulations (and not the experiment).

Moving the reflex to global does not solve the general problem since it was placed in the experiment because I want it to execute at the end of each simulation (for example saving the results of the simulation). It would require me to write an additional stop check beside the until facet in the global and put this reflex in there.

**Comment by AlexisDrogoul** [comment]
> Moving the reflex to global does not solve the general problem since it was placed in the experiment because I want it to execute at the end of each simulation (for example saving the results of the simulation). It would require me to write an additional stop check beside the until facet in the global and put this reflex in there.

This issue is solved AFAIK. Your comment is a different question. If you want to do something at the end of a simulation (or at the death of an agent), use an `abort` reflex within the simulations. That will probably work for your case.
